# Simple workflow for deploying static content to GitHub Pages
name: Generate and Deploy Doxygen Docs to Pages

on:
  workflow_dispatch:

# Sets permissions of the GITHUB_TOKEN to allow deployment to GitHub Pages
permissions:
  contents: read
  pages: write
  id-token: write

# Allow only one concurrent deployment, skipping runs queued between the run in-progress and latest queued.
# However, do NOT cancel in-progress runs as we want to allow these production deployments to complete.
concurrency:
  group: "pages"
  cancel-in-progress: false
  
env:
  dotnet-version: "9.0.x"

jobs:
  # Single deploy job since we're just deploying
  deploy:
    environment:
      name: github-pages
      url: ${{ steps.deployment.outputs.page_url }}
    runs-on: ubuntu-latest
    if: ${{ contains(github.server_url, 'github.com') }}
    steps:
      - name: Checkout
        uses: actions/checkout@v4
      - name: Setup Pages
        uses: actions/configure-pages@v5
      - name: Install Doxygen
        run: sudo apt-get update && sudo apt-get install -y doxygen
      - name: Setup .NET Core SDK ${{ env.dotnet-version }}
        uses: actions/setup-dotnet@v4
        with:
          dotnet-version: ${{ env.dotnet-version }}
      - name: Restore dependencies
        run: dotnet restore
      - name: Build Solution and Generate XML Docs
        run: dotnet build --configuration Release --no-restore --verbosity quiet
      - name: Generate Documentation with Doxygen
        run: doxygen
      - name: Upload artifact
        uses: actions/upload-pages-artifact@v3
        with:
          path: './doxygen-generated/html'
      - name: Deploy to GitHub Pages
        id: deployment
        uses: actions/deploy-pages@v4
