# This workflow will build a .NET project
# For more information see: https://docs.github.com/en/actions/automating-builds-and-tests/building-and-testing-net

name: Prerelease

on:
  push:
    branches-ignore: [ "master" ]
  pull_request:
    branches-ignore: [ "master" ]


env:
  VERSION: "0.4.1"
  DOTNETVERSION: "net9.0"
  RUNNER_TOOL_CACHE: /toolcache
  ACTIONS_STEP_DEBUG: true
  dotnet-version: "9.0.x"

jobs:
  detect-platform:
    runs-on: ubuntu-latest
    if: ${{ contains(github.server_url, 'github.com') }}
    steps:
      - name: Check out the repository
        uses: actions/checkout@v4
      - name: List all environment variables
        run: printenv | sort
      - name: Detect if running on GitHub
        if: ${{ contains(github.server_url, 'github.com') }}
        run: echo "Running on GitHub Actions"
                 
  build:
    env:
      RUNNER_TOOL_CACHE: /toolcache
    strategy:
      matrix:
        os: [ ubuntu-latest ]
    runs-on: ${{ matrix.os }}
    needs: [detect-platform]
    if: ${{ contains(github.server_url, 'github.com') }}
    steps:
    - name: bash-logs
      run: set -x
    - uses: actions/checkout@v4
    - name: Setup .NET Core SDK ${{ env.dotnet-version }}
      uses: actions/setup-dotnet@v4
      with:
        dotnet-version: ${{ env.dotnet-version }}  
    - name: Restore dependencies
      run: dotnet restore
    - name: Build release
      run: dotnet build --configuration Release --no-restore --verbosity quiet
    - name: Build debug
      run: dotnet build --configuration Debug --no-restore --verbosity quiet
    - name: "List all files"
      run: | 
        ls -R
        dotnet --info
    - name: Test
      run: dotnet test --no-build --verbosity quiet --framework ${{ env.DOTNETVERSION }}
      continue-on-error: true
    - name: Display dotnet version
      run: dotnet --version
    - name: "List all files"
      run: ls -R
      
  release:
    env:
      RUNNER_TOOL_CACHE: /toolcache
    strategy:
      matrix:
        os: [ ubuntu-latest ]
      fail-fast: false
    runs-on: ${{ matrix.os }}
    needs: [build]
    if: ${{ needs.build.result == 'success' && contains(github.server_url, 'github.com') }}
    steps:
    - name: bash-logs
      run: set -x
    - uses: actions/checkout@v4
    - name: Setup dotnet
      uses: actions/setup-dotnet@v4
      with:
        dotnet-version: ${{ env.dotnet-version }}
    - name: Restore dependencies
      run: dotnet restore
    - name: Publish
      run: |
        dotnet publish bookmark-dlp/bookmark-dlp.csproj --configuration Release --runtime win-x64 --self-contained --framework ${{ env.DOTNETVERSION }}
        dotnet publish bookmark-dlp/bookmark-dlp.csproj --configuration Release --runtime win-x86 --self-contained --framework ${{ env.DOTNETVERSION }}
        dotnet publish bookmark-dlp/bookmark-dlp.csproj --configuration Release --runtime win-arm64 --self-contained --framework ${{ env.DOTNETVERSION }}
        dotnet publish bookmark-dlp/bookmark-dlp.csproj --configuration Release --runtime linux-x64 --self-contained --framework ${{ env.DOTNETVERSION }}
        dotnet publish bookmark-dlp/bookmark-dlp.csproj --configuration Release --runtime linux-arm64 --self-contained --framework ${{ env.DOTNETVERSION }}
        dotnet publish bookmark-dlp/bookmark-dlp.csproj --configuration Release --runtime osx-x64 --self-contained --framework ${{ env.DOTNETVERSION }}
        dotnet publish bookmark-dlp/bookmark-dlp.csproj --configuration Release --runtime osx-arm64 --self-contained --framework ${{ env.DOTNETVERSION }}
    - name: "List all files"
      run: |
        echo $PWD
        ls -R
    - name: "Rename based on architecture"
      run: |
        cd /home/runner/work/bookmark-dlp/bookmark-dlp
        mkdir releases
        mv "./bookmark-dlp/bin/Release/net9.0/win-x64/publish/bookmark-dlp.exe" "./releases/bookmark-dlp-win-x64-${{ env.VERSION }}.exe"
        mv "./bookmark-dlp/bin/Release/net9.0/win-x86/publish/bookmark-dlp.exe" "./releases/bookmark-dlp-win-x86-${{ env.VERSION }}.exe"
        mv "./bookmark-dlp/bin/Release/net9.0/linux-arm64/publish/bookmark-dlp" "./releases/bookmark-dlp-linux-arm64-${{ env.VERSION }}"
        mv "./bookmark-dlp/bin/Release/net9.0/linux-x64/publish/bookmark-dlp" "./releases/bookmark-dlp-linux-x64-${{ env.VERSION }}"
        mv "./bookmark-dlp/bin/Release/net9.0/osx-x64/publish/bookmark-dlp" "./releases/bookmark-dlp-osx-x64-${{ env.VERSION }}"
        mv "./bookmark-dlp/bin/Release/net9.0/osx-arm64/publish/bookmark-dlp" "./releases/bookmark-dlp-osx-arm64-${{ env.VERSION }}"
        mv "./bookmark-dlp/bin/Release/net9.0/win-arm64/publish/bookmark-dlp.exe" "./releases/bookmark-dlp-win-arm64-${{ env.VERSION }}.exe"
        cd releases
        ls -lah
    - name: "Delete old release"
      env:
        GH_TOKEN: ${{ github.token }}
        VERSION: ${{ env.VERSION }}
      run: |
        echo "Running on GitHub Actions"
        gh release list > releases.txt
        cat releases.txt
        echo "Version to delete: $VERSION"
        if grep -w "$VERSION" releases.txt; then
          echo "Release $VERSION found. Deleting..."
          gh release delete "$VERSION" --yes
        else
          echo "Release $VERSION not found. Skipping deletion."
        fi
    - name: "Create new pre-release GH"
      env:
        GH_TOKEN: ${{ github.token }}
        VERSION: ${{ env.VERSION }}
      run: |
        set -x
        echo "Creating prerelease for version: $VERSION"
        gh release create "$VERSION" --target unstable --prerelease --title "Development build $VERSION" --generate-notes
    - name: Upload
      env:
        GH_TOKEN: ${{ github.token }}
      run: |
        ls -lah ./releases/
        gh release upload "${{ env.VERSION }}" "./releases/bookmark-dlp-win-x64-${{ env.VERSION }}.exe" --clobber
        gh release upload "${{ env.VERSION }}" "./releases/bookmark-dlp-win-x86-${{ env.VERSION }}.exe" --clobber
        gh release upload "${{ env.VERSION }}" "./releases/bookmark-dlp-linux-arm64-${{ env.VERSION }}" --clobber
        gh release upload "${{ env.VERSION }}" "./releases/bookmark-dlp-linux-x64-${{ env.VERSION }}" --clobber
        gh release upload "${{ env.VERSION }}" "./releases/bookmark-dlp-osx-x64-${{ env.VERSION }}" --clobber
        gh release upload "${{ env.VERSION }}" "./releases/bookmark-dlp-osx-arm64-${{ env.VERSION }}" --clobber
        gh release upload "${{ env.VERSION }}" "./releases/bookmark-dlp-win-arm64-${{ env.VERSION }}.exe" --clobber   
          
  pupnet:
    env:
      RUNNER_TOOL_CACHE: /toolcache
    strategy:
      matrix:
        os: [ ubuntu-latest ]
      fail-fast: false
    runs-on: ${{ matrix.os }}
    needs: [release]
    if: ${{ needs.release.result == 'success' }}
    steps:
    - uses: actions/checkout@v4
    - name: Setup dotnet
      uses: actions/setup-dotnet@v4
      with:
        dotnet-version: |
          ${{ env.dotnet-version }}
          8.0.x
    - name: Setup dependencies
      run: |
        # dnf -y install dpkg rpmdevtools # flatpak flatpak-builder pandoc
        sudo apt-get update
        sudo apt-get -y install dpkg rpm flatpak flatpak-builder pandoc libfuse2
        sudo flatpak remote-add --if-not-exists flathub https://dl.flathub.org/repo/flathub.flatpakrepo
        sudo flatpak install -y flathub org.freedesktop.Platform//24.08 org.freedesktop.Sdk//24.08
        dotnet tool install -g Neurofibromin.PupNet
    - name: Restore dependencies
      run: dotnet restore
    - name: Publish
      run: |
        # dotnet publish bookmark-dlp.sln --configuration Release --runtime win-x64 --self-contained
        # runtime: [ 'linux-x64', 'linux-arm64' ]
        # kind: [ 'appimage', 'deb', 'rpm', 'flatpak' ]
        pupnet --runtime linux-x64 --kind appimage --build Release --app-version ${{ env.VERSION }} --verbose
        pupnet --runtime linux-x64 --kind deb --build Release --app-version ${{ env.VERSION }} --verbose
        pupnet --runtime linux-x64 --kind rpm --build Release --app-version ${{ env.VERSION }} --verbose
        pupnet --runtime linux-x64 --kind flatpak --build Release --app-version ${{ env.VERSION }} --verbose
        pupnet --runtime linux-arm64 --kind appimage --build Release --app-version ${{ env.VERSION }} --verbose
        pupnet --runtime linux-arm64 --kind deb --build Release --app-version ${{ env.VERSION }} --verbose
        # pupnet --runtime linux-arm64 --kind rpm --build Release --app-version ${{ env.VERSION }} --verbose
        pupnet --runtime linux-arm64 --kind flatpak --build Release --app-version ${{ env.VERSION }} --verbose
    - name: "List all files"
      run: |
        echo $PWD
        ls -R
        # no need to rename, pupnet names things according to conventions
        # no need to delete/create release here, it was resolved in "release" job
    - name: Sign rpm
      run: |
        mkdir -p ~/.gnupg
        chmod 700 ~/.gnupg
        cd ~
        cat <<EOF > ~/.rpmmacros
        %_signature gpg
        %_gpg_path ${PWD}/.gnupg
        %_gpg_name Neurofibromin-CICD-Autosign
        %_gpgbin /usr/bin/gpg
        EOF
        gpgconf --launch gpg-agent
        echo "${{ secrets.GPG_KEY_AUTOSIGN_PRIVATE }}" | gpg --import
        gpg --export -a '5C85EF4F34E089A04B2063A5833E01FC62E56779' > RPM-GPG-KEY
        rpm --import RPM-GPG-KEY
        rpm -q gpg-pubkey --qf '%{name}-%{version}-%{release} --> %{summary}\n'
        cd /home/runner/work/bookmark-dlp/bookmark-dlp
        rpm --addsign ./pupnet/out/bookmark-dlp_${{ env.VERSION }}-1.x86_64.rpm
    - name: Upload
      env:
        GH_TOKEN: ${{ github.token }}
      run: |
        # gh release upload "${{ env.VERSION }}" "./pupnet/out/*" --clobber

        gh release upload "${{ env.VERSION }}" ./pupnet/out/bookmark-dlp-${{ env.VERSION }}-1.aarch64.flatpak --clobber         
        gh release upload "${{ env.VERSION }}" ./pupnet/out/bookmark-dlp-${{ env.VERSION }}-1.x86_64.flatpak --clobber

        gh release upload "${{ env.VERSION }}" ./pupnet/out/bookmark-dlp-${{ env.VERSION }}-1.x86_64.AppImage --clobber

        gh release upload "${{ env.VERSION }}" ./pupnet/out/bookmark-dlp_${{ env.VERSION }}-1.x86_64.rpm --clobber

        gh release upload "${{ env.VERSION }}" ./pupnet/out/bookmark-dlp_${{ env.VERSION }}-1_amd64.deb --clobber
        gh release upload "${{ env.VERSION }}" ./pupnet/out/bookmark-dlp_${{ env.VERSION }}-1_arm64.deb --clobber
        
  pupnet-innosetup:
    env:
      RUNNER_TOOL_CACHE: /toolcache
    strategy:
      matrix:
        os: [ windows-latest ]
      fail-fast: false
    runs-on: ${{ matrix.os }}
    needs: [ pupnet ]
    if: ${{ needs.pupnet.result == 'success' }}
    steps:
      - uses: actions/checkout@v4
      - name: Setup dotnet
        uses: actions/setup-dotnet@v4
        with:
          dotnet-version: |
            ${{ env.dotnet-version }}
            8.0.x
      - name: Setup PupNet
        run: |
          dotnet tool install -g Neurofibromin.PupNet
      - name: Restore dependencies
        run: dotnet restore
      - name: Publish
        run: |
          # dotnet publish bookmark-dlp.sln --configuration Release --runtime win-x64 --self-contained
          # runtime: [ 'linux-x64', 'linux-arm64' ]
          # kind: [ 'appimage', 'deb', 'rpm', 'flatpak' ]
          pupnet --runtime win-x64 --kind setup --build Release --app-version ${{ env.VERSION }} --verbose
          pupnet --runtime win-x86 --kind setup --build Release --app-version ${{ env.VERSION }} --verbose
      - name: List all files
        run: |
          echo $PWD
          ls -R
      - name: Upload
        env:
          GH_TOKEN: ${{ github.token }}
        run: |
          # gh release upload "${{ env.VERSION }}" "./pupnet/out/*" --clobber
          gh release upload "${{ env.VERSION }}" ./pupnet/out/bookmark-dlpSetup-${{ env.VERSION }}-1.x64.exe --clobber
          gh release upload "${{ env.VERSION }}" ./pupnet/out/bookmark-dlpSetup-${{ env.VERSION }}-1.x86.exe --clobber
              
  calculate-hash:
    env:
      RUNNER_TOOL_CACHE: /toolcache
    strategy:
      matrix:
        os: [ ubuntu-latest ]
      fail-fast: false
    runs-on: ${{ matrix.os }}
    needs: [ pupnet-innosetup ]
    if: ${{ needs.pupnet-innosetup.result == 'success' }}
    steps:        
      - name: Calculate hash
        uses: thewh1teagle/checksum@v1
        env:
          GH_TOKEN: ${{ secrets.GITHUB_TOKEN }}
        with:
          algorithm: sha256
          tag: ${{ env.VERSION }}
          pre-release: true
          
  
    
    #comments  https://github.com/seerge/g-helper/blob/main/.github/workflows/release.yml
    # Optional global.json location, if your global.json isn't located in the root of the repo.
    #global-json-file:
    # Optional package source for which to set up authentication. Will consult any existing NuGet.config in the root of the repo and provide a temporary NuGet.config using the NUGET_AUTH_TOKEN environment variable as a ClearTextPassword
    #source-url:
    # Optional NuGet.config location, if your NuGet.config isn't located in the root of the repo.
    #config-file: # optional
